### ISSUE TITLE
稍微改动一下就可以添加导出全部聊天的功能

### ISSUE THREAD

**Issue by 3210448723** [f13T2ach/WxMsgDump#8]
只要在Main.py中的第134行
`if chat[3]==aimChat or chat[2]==aimChat:`
改成
`if aimChat == 'ALL' or chat[3]==aimChat or chat[2]==aimChat:`
改动后
```
[+]请输入要导出的聊天名称，或者你给他/她的备注。空表示退出操作
[>]ALL
```
输入ALL即可

**Comment by f13T2ach** [comment]
感谢你的建议，我将考虑在下一版本(V1.2)加入此功能。
